# train, validation setting for each model
---
wsss:
  side_length: 224
  stride: 75
  num_class: 3
  mean: [0.678,0.505,0.735]
  std: [0.144,0.208,0.174]

warwick:
  side_length: 112
  stride: 112
  num_class: 2
  mean: [0.787, 0.511, 0.785]
  std: [0.167, 0.248, 0.131]

crag:
  side_length: 112
  stride: 56
  num_class: 2
  mean: [0.831, 0.725, 0.858]
  std: [0.133, 0.173, 0.099]

network_image_size: 224
scales: [1, 1.25, 1.5, 1.75, 2]